[package]
name = "capnpc-plain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
capnp-plain = { path = "../capnp-plain" }
convert_case = { workspace = true }
once_cell = { workspace = true }
prettyplease = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
serde = { workspace = true, features = [ "derive" ]}
syn = { workspace = true }
