[package]
name = "capnpc-plain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
capnp-plain = { path = "../capnp-plain" }
convert_case = "0.7.0"
once_cell = "1.19.0"
prettyplease = "0.2.19"
proc-macro2 = "1.0.81"
quote = "1.0.36"
serde = { version = "1.0.200", features = [ "derive" ]}
syn = "2.0.60"
