name: Build Capnproto
description: "Build Capnproto from submodule source code."
runs:
  using: "composite"
  steps:
    - name: Get capnp commit SHA
      id: get-capnp-sha
      shell: bash
      run: |
        capnp_sha=$(git -C third_party/capnproto/ rev-parse HEAD)
        echo "CAPNP_COMMIT_SHA=$capnp_sha" >> "$GITHUB_OUTPUT"
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/bazel
        key: ${{ runner.os }}-bazel-${{ steps.get-capnp-sha.outputs.CAPNP_COMMIT_SHA }}
        restore-keys: ${{ runner.os }}-bazel-
    - name: Build capnp
      shell: bash
      working-directory: third_party/capnproto/c++/src/capnp
      env:
        NPM_CONFIG_PREFIX: ~/.npm-global
      run: bazelisk build :capnp_tool
