name: Build Capnproto
description: "Build Capnproto from submodule source code"
runs:
  using: "composite"
  steps:
    - name: Get capnp commit SHA
      id: get-capnp-sha
      run: |
        capnp_sha=$(git -C third_party/capnproto/ rev-parse HEAD)
        echo "CAPNP_COMMIT_SHA=$capnp_sha" >> "$GITHUB_OUTPUT"
    - uses: actions/cache@v3
      with:
        path: |
          third_party/capnproto/c++/bazel-bin
          third_party/capnproto/c++/bazel-c++
          third_party/capnproto/c++/bazel-out
        key: ${{ runner.os }}-bazel-${{ steps.get-capnp-sha.outputs.CAPNP_COMMIT_SHA }}
        restore-keys: ${{ runner.os }}-bazel-
    - name: Install bazel
      run: npm install -g @bazel/bazelisk
    - name: Build capnp
      working-directory: third_party/capnproto/c++/src/capnp
      run: bazelisk build :capnp_tool
