name: Integration Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: actions/setup-node@v4
      - uses: ./.github/actions/cache-cargo
      - uses: ./.github/actions/build-capnp
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Check self-hosting
        working-directory: crates/capnpc-plain/src/schema
        run: |
          cp schema_capnp.rs schema_capnp_main.rs
          sh build.sh
          diff schema_capnp_main.rs schema_capnp.rs
      - name: Check golden schema
        working-directory: crates/golden/src/schema
        run: |
          cp test_capnp.rs test_capnp_main.rs
          sh build.sh
          cargo fmt
          diff test_capnp_main.rs test_capnp.rs
      - name: Golden test
        working-directory: crates/golden
        run: cargo test
