name: Unit Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cache-cargo
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
      - run: cargo test --workspace --exclude capnp-plain-golden
